# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: asking_agree
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: boast
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: complain
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: indifference
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: suggest
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: appraise

policies:
   - name: MemoizationPolicy
     max_history: 5
   - name: TEDPolicy
     max_history: 5
     epochs: 100
   - name: RulePolicy
     core_fallback_threshold: 0.4
     core_fallback_action_name: "action_custom_fallback"
     enable_fallback_prediction: True
